### ISSUE TITLE
Dynamic Graph Creation

### ISSUE THREAD

**Issue by ashfaq92** [jelmerk/hnswlib#14]
Hi, Thanks for great work!
Please guide if there a method to make graph without specifying its `maxItemCount` in advance.
thanks again. and lots of love

**Comment by jelmerk** [comment]
Not right now (because the original c++ version did not have  it)

It's on my list of things to eventually work out

**Comment by ashfaq92** [comment]
Actually in my research domain, initially graph size is unknown. We have to add elements/nodes incrementally. If we give initially maximum affordable size i.e Integer.MAX_VALUE, initial indexing takes huge time.

**Comment by asad-awadia** [comment]
@jelmerk is it possible now? To either not give the maxItemCount or add more items than specified?
