### ISSUE TITLE
Option for Selecting Neighbors Simply or by Heuristic

### ISSUE THREAD

**Issue by ashfaq92** [jelmerk/hnswlib#17]
Hi, thanks for great work.
In this implementation, can we use _heuristic_ for selecting neighbors for a point optionally? I mean, there are some cases when user want to use simple method of selecting neighbors instead of using heuristic. I did not see any option in Readme file, documentation or in examples section, please guide. As a humble suggestion, we can set a (flag or option) for which method should be used for selecting nearest neighbors while initializing the index. Thank you!

**Comment by jelmerk** [comment]
You mean returning a dynamic number of nearest neighbors instead of using a hardcoded number ?

**Comment by ashfaq92** [comment]
i mean there are two algorithms for inserting a vector into HNSW Graph. One is simple and other option uses 'heuristic'. By default, i think your implementation uses 'heuristic' method. But what if somebody needs simple method for inserting a vector. I dont see any facility for that. For details, i refer to HNSW paper

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jelmerk** [comment]
Oh like so. I had it at some point but removed it because it just about always performed worse and i did not want to add the complexity

**Comment by ashfaq92** [comment]
it performs worst on static dataset. But HNSW can be used in incremental datasets and I am using another algorithm for removing clustering. Please add it again. Because this code has other wide implementations

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
