### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable. I am using Pyspark

### ISSUE THREAD

**Issue by DoanThu** [jelmerk/hnswlib#2]
Hi, I ran 
**spark-submit --py-files hnswlib-pyspark/dist/pyspark_hnsw-0.1-*.egg  --jars hnswlib-spark/target/hnswlib-spark-*-jar-with-dependencies.jar <my_script>**
And get this error

> File "/home/ubuntu/miniconda/envs/thu_env/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/__init__.py", line 105, in wrapper
  File "/home/ubuntu/miniconda/envs/thu_env/lib/python3.7/site-packages/pyspark_hnsw/hnsw.py", line 13, in __init__
    self._java_obj = self._new_java_obj("com.github.jelmerk.knn.spark.hnsw.Hnsw", self.uid)
  File "/home/ubuntu/miniconda/envs/thu_env/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 63, in _new_java_obj
TypeError: 'JavaPackage' object is not callable
Exception ignored in: <function JavaParams.__del__ at 0x7f5dbacb7620>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/thu_env/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 105, in __del__
  File "/home/ubuntu/miniconda/envs/thu_env/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1897, in detach
AttributeError: 'NoneType' object has no attribute '_detach'

Can you please help me with this?

**Comment by jelmerk** [comment]
Using the published packages like this would be the preferred way to use this lib

```
pip install pyspark-hnsw
spark-submit --packages 'com.github.jelmerk:hnswlib-spark_2.3.0_2.11:0.0.20' <my_script>
```
Is there any reason you cannot do that ? I think you get this error if it cannot find the java classes so maybe hnswlib-spark/target/hnswlib-spark--jar-with-dependencies.jar is not findable ?

**Comment by DoanThu** [comment]
Thank you @jelmerk . It works now. I was confused because the instruction from hnswlib and hnswlib-pyspark were inconsistant. 
Btw, after the code runs successfully, do you have any example to read index file and seek for k-nearest neighbors?

**Comment by jelmerk** [comment]
I am not sure what it is you are asking

There is example code for the java and scala api's in

https://github.com/jelmerk/hnswlib/tree/master/hnswlib-examples

For spark you can look at the test

https://github.com/jelmerk/hnswlib/blob/master/hnswlib-spark/src/test/scala/com/github/jelmerk/knn/spark/hnsw/HnswSpec.scala

How you save and load a standalone index can be seen in this test

https://github.com/jelmerk/hnswlib/blob/master/hnswlib-core/src/test/java/com/github/jelmerk/knn/hnsw/HnswIndexTest.java#L186
