### ISSUE TITLE
A method for loading a large index

### ISSUE THREAD

**Issue by drubinstein** [jelmerk/hnswlib#22]
I'm working with a large index (~11G and will most likely grow more in the future). It is inefficient for my use case to load the entire index into memory (as this library requires). Do you have any recommendations on how to handle a large index or any plans to add ways to not load the entire index into memory in the future?

Thanks and thanks for making this library.

**Comment by jelmerk** [comment]
Hi @drubinstein ,  I have no plans to make it possible to not load the entire index into memory. Attempting something like that is unlikely to perform well. Ram is cheap nowadays and will only continue to get cheaper. 

If you don't have access to machines with more memory your best option would be to shard your index. Eg. store 50% of your values in an index on machine A and 50% of your values on machine B, then when querying, query both indices, merge the resultlists order by score and keep the k closest results.

This is for example how the spark module in this project works
