### ISSUE TITLE
Question about retrieving 1M topK items from 100M pool?

### ISSUE THREAD

**Issue by alice2008** [jelmerk/hnswlib#28]
Thanks a lot for the great library! We have been using the hnswlib for some time and quite satisfied with the retrieval quality. I have a question as posted in the title: is this possible to retrieve 1M topK items from 100M pool (vector dim = 100)? I have been told it is almost impossible to construct the search layer graph. Is this true? If so, I am curious to know where is the true bottleneck. We can sacrifice the recall in this case.

**Comment by alice2008** [comment]
I read the HNSW paper and have some questions to understand the bottleneck of retrieving topK=1M from 100M. I really appreciate if you can help me sort this through.

1. The paper states that when a query comes, it would go over layers from top to bottom and retrieve the desired candidates from the bottom layer.
2. This indicates the bottom layer would need to contain at least 1M nodes (ef and efConstruction parameters in the paper)
3. Assume each sub graph have 1M nodes and each node has 5 connections (neighbors). Each sub graph memory storage is 1M * 5 * 4bytes = 20MB which does sounds not too bad. I am not sure how to estimate the overall graph footprint given each node might repeated several times across graphs.  There would be at least 100M/1M = 100 sub graphs. And assume each node repeated 5 times. Total memory footprint of overall graph would be 100 * 5 * 20MB = 10GB. But I think the bottom subgraphs probably can stored in distributed fashion.

Can you help me where are the technical challenges?  (1) memory limitation of storing the graph given large topK; or (2) traversing the graph from top to bottom would result too many data shuffle?; or (3) it is purely infeasible to construct the subgraph contains 1M nodes?

**Comment by jelmerk** [comment]
I am not sure if I understand the question.  

do you want to do a single search where K = 1M 
or do you want to do 1M top K searches and K is small
