### ISSUE TITLE
how can save datalabel corespond to the vector?

### ISSUE THREAD

**Issue by yuanjun1991** [jelmerk/hnswlib#29]
hi,thank you for your attention
i just review the source code of your java implementation for hnswlib ,i just wonder how can i save vectors with labels? 
eg:
hnswIndex.add(vec1,label1)

**Comment by jelmerk** [comment]
You mean take the items out of the index ?

You can call items() on it 

https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/jelmerk/hnswlib-core/0.0.46/hnswlib-core-0.0.46-javadoc.jar/!/index.html

**Comment by yuanjun1991** [comment]
no ,i mean how can i add an item into the index with specialed id or label,when call the method pass two parametres the vector and the specialed id or label like:
hnswIndex.add(vec1,label1)

**Comment by jelmerk** [comment]
The items you put in the index must implement Item

https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/jelmerk/hnswlib-core/0.0.46/hnswlib-core-0.0.46-javadoc.jar/!/com/github/jelmerk/knn/Item.html

The id would be what you refer to as a label
