### ISSUE TITLE
how to delete an item from the index

### ISSUE THREAD

**Issue by yuanjun1991** [jelmerk/hnswlib#30]
hi ,thanks for your greate work!
how to delete an item from the index,i know there is a method remove(),but i dont know the second parameters means and how can i get the parametres :version

hnswindex,remove(String ids,Long version)

**Comment by jelmerk** [comment]
It's described in the documentation

https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/jelmerk/hnswlib-core/0.0.46/hnswlib-core-0.0.46-javadoc.jar/!/com/github/jelmerk/knn/hnsw/HnswIndex.html#remove-TId-long-

If you don't use version in your Item, pass in zero. 

Word of caution about deletes. while they make it so the item does not get found anymore it does not free up memory.  
and if you permanently want to get rid of deletes you have to create a new index with the items of the old index
