### ISSUE TITLE
Deadlock when Errors are thrown

### ISSUE THREAD

**Issue by nur1popcorn** [jelmerk/hnswlib#32]
Errors just like runtime exceptions can be thrown without being declared in the method's header explicitly (e.g. AssertionError, ...). I noticed that the addAll method in the Index interface only handles RuntimeExceptions however. So if an an item is added and that causes an Error to be thrown the program deadlocks. Initially I thought that this would be rather easy to fix it turns out however that the caught RuntimeException is later rethrown. Therefore fixing the bug and keeping that functionality would require that addAll throws Throwable which is not very beautiful and also breaks compatibility with existing applications.

Below is an example which reliably deadlocks:
```java
try {
    DistanceFunction<Object, Integer> distanceFunction = (a, b) -> { throw new Error(); };
    HnswIndex<Object, Object, Item<Object, Object>, Integer> index =
        HnswIndex.newBuilder(1, distanceFunction, 2)
            .build();
    class ObjectItem implements Item<Object, Object> {
        private final Object object = new Object();
        @Override
        public Object id() { return object; }
        @Override
        public Object vector() { return object; }
        @Override
        public int dimensions() { return 1; }
    }
    index.addAll(List.of(new ObjectItem(), new ObjectItem()));
} catch (InterruptedException e) {
    e.printStackTrace();
}
 ```

**Comment by jelmerk** [comment]
Errors are thrown by the JVM to indicate serious problems that are not intended to be handled by an application

**Comment by nur1popcorn** [comment]
While I agree with you that errors should not be handled by the application I do think that them resulting in a deadlock is not really nice either. I believe that most people want their application to crash if something like that occurs (or at least not deadlock xD). Anyways i have decided to fix the issue for myself and have created a pull request.
