### ISSUE TITLE
Has anyone tried Kryo serialization for Save and load?

### ISSUE THREAD

**Issue by xiaoyoupei** [jelmerk/hnswlib#37]
As shown in the topic

**Comment by jelmerk** [comment]
You mean for spark ? Is it failing for you ? I used to have an implementation of KryoRegistrator in the project but I think I removed it because I thought it was no longer needed.

**Comment by xiaoyoupei** [comment]
@jelmerk 
It's a pure Java project, but it doesn't know how to change the serialization of hnswlib itself.I hope you can give me some advice.Because I wanted to use Kryo to see if I could improve the performance of save and load.

**Comment by jelmerk** [comment]
I don't think using kryo will speed things up

https://github.com/jelmerk/hnswlib/blob/master/hnswlib- as I use[ custom java serialisation](core/src/main/java/com/github/jelmerk/knn/hnsw/HnswIndex.java#L731) that should always be faster.

The one thing it still uses java serialization for (and where you can optimize for speed) is the serialization of keys and items

You can create your own implementations of [com.github.jelmerk.knn.ObjectSerializer](https://github.com/jelmerk/hnswlib/blob/master/hnswlib-core/src/main/java/com/github/jelmerk/knn/ObjectSerializer.java)

And pass those to the `withCustomSerializers` method when constructing the index

**Comment by jelmerk** [comment]
For example this hives you the same behavior as the default
```
        DistanceFunction<float[], Float> distanceFunction = DistanceFunctions.FLOAT_COSINE_DISTANCE
        ObjectSerializer<String> itemIdSerializer = new JavaObjectSerializer<>();
        ObjectSerializer<TestItem> itemSerializer = new JavaObjectSerializer<>();

        HnswIndex
                .newBuilder(dimensions, distanceFunction, maxItemCount)
                .withCustomSerializers(itemIdSerializer, itemSerializer)
                .build();
```

You replace itemIdSerializer and itemSerializer with something more efficient to speed things up

**Comment by xiaoyoupei** [comment]
Thank you for your patient guidance. I will try and give you a reply.

**Comment by xiaoyoupei** [comment]
[https://github.com/xiaoyoupei/hnswlibtest/tree/master/hnswlib-core/src/main/java/com/github/jelmerk/knn/hnsw](url)
I have uploaded the ObjectSerializer to my warehouse, you can have a look at it when you have time.There is still a problem with saveAndLoadIndex in test. I hope you can provide some answers.

**Comment by jelmerk** [comment]
you checked in all the code as one big commit making it super hard to see what you actually changed.

if you want me to take a look at something please clone the repo and do your changes in separate commits

**Comment by xiaoyoupei** [comment]
I'm terribly sorry.I just implemented Kryo on the ObjectSerializr interface in HNSWlib-core

**Comment by jelmerk** [comment]
saving the index is done on a single thread, you can probably reuse your kryo instance

**Comment by jelmerk** [comment]
Anyway try and write some tests / do some benchmarking vs the java serialiser if this is what you want to do

For the best performance you'd probably have to write something custom and not use kryo, or at least thats what we did in prod

**Comment by xiaoyoupei** [comment]
Ok, thank you very much. I will try further.
