### ISSUE TITLE
How to find nearest neighbors of an item that does not appear in index process?

### ISSUE THREAD

**Issue by DoanThu** [jelmerk/hnswlib#4]
I have this dataframe:
![image](https://user-images.githubusercontent.com/15232942/66627284-5ffef400-ec25-11e9-9f0b-4de329fd4c60.png)
And I ran this:
`hnsw = Hnsw(identifierCol='ID', vectorCol='features', distanceFunction='cosine', m=64, ef=5, k=5, efConstruction=200, numPartitions=100)`
`model = hnsw.fit(new_df)`
`model.transform(new_df).write.parquet('output', mode='overwrite')`

Then I read back .parquet files and get:

![image](https://user-images.githubusercontent.com/15232942/66627362-a5bbbc80-ec25-11e9-825f-2a2e241fa70f.png)
My question is, assume that I have an item:
(103, [1, 1])
How can I find nearest neighbors of it?

**Comment by jelmerk** [comment]
it would just show up in the output dataframe..

the neighbors column contains a list of structs that are made up out of an id and a distance to the item

in your example the nearest neighbor of 102 is 101, its distance is 0.002, the seond closest neighbor is 100 whose distance is 0.003

**Comment by DoanThu** [comment]
Thank you for your response. I know if the items have IDs like 100, 101 and 102, their nearest neighbors are showed up on the output dataframe. I just wonder how to find nearest ones from items with different IDs (103, 104, 105, etc).

**Comment by jelmerk** [comment]
I am not sure if i get the question

what you pas to `fit` represents the candidate set. Every item in that dataframe is a candidate neighbor. if 103 is in there it can show up as a nearest neighbor

What you pass to `transform` is the query dataframe. if 103 is in this dataframe but not in the dataframe you pass to `fit ` then you will just get neighbors for this item, You wont but it itself is not a candidate neighbor

**Comment by DoanThu** [comment]
I got it. Just pass to `transform` the query dataframe. Thanks a ton.
