### ISSUE TITLE
mvn test hnsw-spark NormalizerSpec java.lang.NoClassDefFoundError: org/apache/spark/ml/param/shared/HasInputCol

### ISSUE THREAD

**Issue by huzhiyi123** [jelmerk/hnswlib#44]
## Can you help me look at the problem?
I just started learning to use spark and spark-hnsw.
When I mvn test hnsw-spark, NormalizerSpec throw out this error java.lang.NoClassDefFoundError: org/apache/spark/ml/param/shared/HasInputCol.
"mvn clean install -dskiptests" has been done.
I have set dependency> spark-mllib_2.11 compile ,but it doesn`t work.

submit nomalizerSpectest.py --packages 'com.github.jelmerk:hnswlib-spark_2.3_2.11:0.0.49' or 0.50 
donnt work,throw out above problem

What I shound do?
Thanks!

## env 
spark 2.3.0 local model 
OpenJDK 64-Bit Server VM, 1.8.0_232
 Scala version 2.11.12

**Comment by jelmerk** [comment]
Can you try 2 things

1. when compiling instead of running `mvn clean install` can you run `./mvnw clean install`
2. Can you output `spark.version` when running your spark job ? I am not fully convinced you are really running with  spark 2.3.0

**Comment by jelmerk** [comment]
The [last travis build](https://app.travis-ci.com/github/jelmerk/hnswlib/builds/240586265) was green so I suspect it's something with your enviornment

**Comment by huzhiyi123** [comment]
# hnswspark version *    <version>0.0.49-SNAPSHOT</version>

1. I test ./mvnw ,reporting the same  errors.
2. 
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://192.168.31.162:4040
Spark context available as 'sc' (master = local[*], app id = local-1635680126116).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.0
      /_/
         
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_232)
Type in expressions to have them evaluated.
Type :help for more information.


There are two errors thrown out during ./mvnw clean install.
when I delete the first test file(vStatisticsDecoratorSpec),I meet the second error
"NormalizerSpec test
 java.lang.NoClassDefFoundError: org/apache/spark/ml/param/shared/HasInputCol"

Here is the sketch of error info.
Below is the complete error info.

# sketch of error info.
### vStatisticsDecoratorSpec:
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: com/github/jelmerk/knn/metrics/dropwizard/


### NormalizerSpec:
21/10/31 19:23:02 WARN Utils: Your hostname, LAPTOP-K1RS47MN resolves to a loopback address: 127.0.1.1; using 192.168.31.162 instead (on interface wifi0)
21/10/31 19:23:02 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
21/10/31 19:23:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/10/31 19:23:06 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: org/apache/spark/ml/param/shared/HasInputCol




# here is complete error info.

### first error

[INFO] --- scalatest-maven-plugin:1.0:test (test) @ hnswlib-scala_2.11 ---
Discovery starting.
Discovery completed in 272 milliseconds.
Run starting. Expected test count is: 24
HnswIndexSpec:
- retrieve m
- retrieve ef
- change ef
- retrieve efConstruction
- retrieve maxItemCount
- retrieve distanceFunction
- retrieve removeEnabled
- retrieve distance ordering
- retrieve itemIdSerializer
- retrieve itemSerializer
- optionally get non-existent item from index
- optionally get existing item from index
- get existing item from index
- get non-existent item from index
- check if item is contained in index
- get items from index
- retrieve size of index
- remove item from index
- find nearest
- find neighbors
- calls progress listener when indexing
- can load saved index
- can create exact view on hnsw index
StatisticsDecoratorSpec:
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: com/github/jelmerk/knn/metrics/dropwizard/StatisticsDecorator
  at com.github.jelmerk.knn.scalalike.metrics.dropwizard.StatisticsDecorator$.apply(StatisticsDecorator.scala:73)
  at com.github.jelmerk.knn.scalalike.metrics.dropwizard.StatisticsDecoratorSpec$$anonfun$1.apply(StatisticsDecoratorSpec.scala:21)
  at com.github.jelmerk.knn.scalalike.metrics.dropwizard.StatisticsDecoratorSpec$$anonfun$1.apply(StatisticsDecoratorSpec.scala:13)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
  ...
  Cause: java.lang.ClassNotFoundException: com.github.jelmerk.knn.metrics.dropwizard.StatisticsDecorator
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at com.github.jelmerk.knn.scalalike.metrics.dropwizard.StatisticsDecorator$.apply(StatisticsDecorator.scala:73)
  at com.github.jelmerk.knn.scalalike.metrics.dropwizard.StatisticsDecoratorSpec$$anonfun$1.apply(StatisticsDecoratorSpec.scala:21)
  at com.github.jelmerk.knn.scalalike.metrics.dropwizard.StatisticsDecoratorSpec$$anonfun$1.apply(StatisticsDecoratorSpec.scala:13)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hnswlib 0.0.49-SNAPSHOT ............................ SUCCESS [  1.975 s]
[INFO] hnswlib-utils ...................................... SUCCESS [  6.728 s]
[INFO] hnswlib-core ....................................... SUCCESS [  8.500 s]
[INFO] hnswlib-metrics-dropwizard ......................... SUCCESS [  6.477 s]
[INFO] hnswlib-scala_2.11 ................................. FAILURE [ 28.262 s]
[INFO] hnswlib-spark_2.3.0_2.11 ........................... SKIPPED
[INFO] hnswlib-examples-parent-pom ........................ SKIPPED
[INFO] hnswlib-examples-java .............................. SKIPPED
[INFO] hnswlib-examples-scala 0.0.49-SNAPSHOT ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.465 s
[INFO] Finished at: 2021-10-31T19:16:46+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project hnswlib-scala_2.11: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hnswlib-scala_2.11

### second error
INFO] --- scalatest-maven-plugin:1.0:test (test) @ hnswlib-spark_2.3.0_2.11 ---
Discovery starting.
Discovery completed in 711 milliseconds.
Run starting. Expected test count is: 9
NormalizerSpec:
21/10/31 19:23:02 WARN Utils: Your hostname, LAPTOP-K1RS47MN resolves to a loopback address: 127.0.1.1; using 192.168.31.162 instead (on interface wifi0)
21/10/31 19:23:02 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
21/10/31 19:23:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/10/31 19:23:06 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: org/apache/spark/ml/param/shared/HasInputCol
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  ...
  Cause: java.lang.ClassNotFoundException: org.apache.spark.ml.param.shared.HasInputCol
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hnswlib 0.0.49-SNAPSHOT ............................ SUCCESS [  2.030 s]
[INFO] hnswlib-utils ...................................... SUCCESS [  6.706 s]
[INFO] hnswlib-core ....................................... SUCCESS [  8.696 s]
[INFO] hnswlib-metrics-dropwizard ......................... SUCCESS [  6.420 s]
[INFO] hnswlib-scala_2.11 ................................. SUCCESS [ 36.518 s]
[INFO] hnswlib-spark_2.3.0_2.11 ........................... FAILURE [ 50.891 s]
[INFO] hnswlib-examples-parent-pom ........................ SKIPPED
[INFO] hnswlib-examples-java .............................. SKIPPED
[INFO] hnswlib-examples-scala 0.0.49-SNAPSHOT ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:52 min
[INFO] Finished at: 2021-10-31T19:23:06+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project hnswlib-spark_2.3.0_2.11: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hnswlib-spark_2.3.0_2.11
➜  hnswspark git:(master) ✗

**Comment by huzhiyi123** [comment]
Here is my test python;

# coding=utf-8

from pyspark_hnsw.linalg import Normalizer
from pyspark.ml.linalg import Vectors
from pyspark.sql import SQLContext
# $example on$
from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import HashingTF, Tokenizer
# $example off$
from pyspark.sql import SparkSession
from pyspark import SparkContext, SparkConf
import findspark
findspark.init() 
def test_normalizer(): #.set('spark.jars.packages', 'com.github.jelmerk:hnswlib-spark_2.3.0_2.11:0.0.50-SNAPSHOT')
    APP_NAME = "mytest"
    conf = (SparkConf().setMaster("local[2]").setAppName(APP_NAME))
    sc = SparkContext(conf=conf)
        
    sql_context = SQLContext(sc)

    df = sql_context.createDataFrame([[Vectors.dense([0.01, 0.02, 0.03])]], ['vector'])

    normalizer = Normalizer(inputCol="vector", outputCol="normalized_vector")

    result = normalizer.transform(df)


    sc.stop()
    assert result.count() == 1

if __name__ == "__main__":
    test_normalizer()

**Comment by asad-awadia** [comment]
@jelmerk how to run maven at all on this? there is no pom file

**Comment by asad-awadia** [comment]
is there no maven dependency i can use to include this in my project?
