### ISSUE TITLE
excludeSelf parameter in hnswlib class not working

### ISSUE THREAD

**Issue by rush4ratio** [jelmerk/hnswlib#47]
When I set excludeSelf to true, it still shows the id's of self in the results. Below is a sample (converted to a pandas dataframe) from what I'm using to experiment:

![image](https://user-images.githubusercontent.com/7237203/150544803-b934aebb-bc65-44af-9876-56ace92edcf7.png)

From above, the id's are on the left while the right contains a list of tuples (id and distance as returned from hnswlib). You'll notice id's of self appearing in the results.

**Comment by jelmerk** [comment]
Can you double check if the id and query  id have the same type?

I am pretty sure this scenario is covered by a unit test, and you can for instance also see it in action in[ this google colab notebook](https://colab.research.google.com/github/jelmerk/hnswlib/blob/master/hnswlib-examples/hnswlib-examples-pyspark-google-colab/quick_start_google_colab.ipynb)

**Comment by rush4ratio** [comment]
Apologies for not getting back to you sooner: It appears, if I set `queryIdentifierCol` to the ID column of interest, then I don't experience the problem of the self ID being included. Was this an additional purpose of `queryIdentifierCol`?

**Comment by jelmerk** [comment]
Yes you need to set the query column or it wont work.. probably i should raise an error if you use excludeSelf without also providing that as it would always be an error

**Comment by rush4ratio** [comment]
I agree that it's not obvious that the query column should be set for excludeSelf to work. If this requirement is not fulfilled, raising an error would help.

**Comment by jelmerk** [comment]
I'll see if i can add that as a safeguard tonight.  and close this issue
