### ISSUE TITLE
benchmark / performance

### ISSUE THREAD

**Issue by maksle** [jelmerk/hnswlib#51]
Hi, 
Are there any performance or benchmark comparisons available already between this library and other ANN libs? I am unsure if references to hnswlib refer to this repo in http://ann-benchmarks.com/glove-100-angular_10_angular.html

**Comment by jelmerk** [comment]
Those benchmarks you referenced are for the original [c++ implementation ](https://github.com/nmslib/hnswlib) which is significantly faster than the java version. I didn't do any benchmarking with other java libs.
