### ISSUE TITLE
PySpark OOM advice

### ISSUE THREAD

**Issue by maksle** [jelmerk/hnswlib#52]
I have the following situation in PySpark:
Cluster with 256GB RAM per node (9GB reserved with rest available to spark) running on 10 nodes with 1 container per node,
~8M rows (candidates df) with a 1024-dim feature vector column with ~10k partitions,
~500M rows (query df) with 1024-dim feature vector column with ~10k partitions,
(edit: they each have ~20k partitions)

An hnsw index using parameters m=12, efConstruction=16, ef=25, the index that gets created is about ~30GB.
I am consistently losing nodes due to memory issues at [KnnAlgorithm.scala:510] or [KnnAlgorithm.scala:521].
It appears it's at the query stage based on the code at those line numbers. 
I increased partition size, reduced the m and efConstruction quite low, and gave generous amounts of RAM.

My only next thought of what to try next was to split up the query df into 1000 dfs and model.transform(df) each one and union them, but I would have thought the large partitioning (10k) would have had the same effect. I also think that would be quite slow if it would even work. After that, I was going to abandon trying to do ANN purely in spark -- perhaps I should create a service that has an nmslib hnsw index and call it with pandas_udf from spark. But before I abandon it, I figured I would see if you have any ideas.

Do you have any suggestions? 
Thank you

**Comment by jelmerk** [comment]
Can you share 

1. the parameters you set on the HnswSimilarity object, in particular the values of numPartitions and numReplicas properties
2. the vector type you are using (double array, float array, ml lib vector etc)

**Comment by maksle** [comment]
```
# using the pyspark_hnsw.conversion.VectorConverter to convert to float which should be faster
converter = VectorConverter(inputCol="tfidf", outputCol="tfidf_f")
# The vectors are normalized, thus inner-product gives cosine distance
hnsw = HnswSimilarity(
    identifierCol="id",
    queryIdentifierCol="id",
    featuresCol="tfidf_f",
    distanceFunction="inner-product",
    m=12,
    ef=25,
    efConstruction=16,
    numPartitions=self.num_partitions,
    k=10,
    excludeSelf=False,
    similarityThreshold=0.30,
    predictionCol="approximate",
)
pipeline = Pipeline(stages=[converter, hnsw])
model = pipeline.fit(candidates)
```

The vectors are ml lib sparse vectors though I'm using the VectorConverter in the pipeline which I think converts them to float.

To be clear, the creation of the model works, and it creates the index which I was able to save and load from (about 30GB in size). The issue happens when I try to query it with the 500M row query dataframe. I did try to split up the query df into smaller dfs with 500_000 rows each, which got through 5 of them before the memory error occurred there as well. I can try with even smaller dfs but this approach is quite slow.  

I've attached the log file. Thank you

[hnswlib-starts-with-partition00.log](https://github.com/jelmerk/hnswlib/files/9500821/hnswlib-starts-with-partition00.log)

**Comment by jelmerk** [comment]
1. Don't convert your inputs. If you use VectorConverter to turn your sparse vector into a float array, which will use more a lot more memory, there are no sparse float vectors datatypes in spark
2. Use a much smaller number of partitions , if you have 20480 partitions it means you will query 20480 indices for every result (unless you prepartition and use setQueryPartitionsCol). 

I would try with say 20 partitions and and 20 executors, then saving the model to disk
Load the index you saved set numReplicas on the loaded model to 2 and query it with 60 executors

**Comment by maksle** [comment]
I will try this today and get back to you in the next couple of days. 

I didn't realize that an index is created for each partition. We use many partitions for all our tasks in this spark job -- even though it's on a unique ID column (or on no column) -- because it helps with OOM errors, and even though bucketing is supposed to help solve that, it never did help me as much as increasing partitions. I think we don't need to use so many partitions though for these candidate/query dataframes since it's reduced to just an id column and a vector column. 

Could you please explain what replicas are/do in this context?

**Comment by jelmerk** [comment]
> Could you please explain what replicas are/do in this context?

During indexing it takes all vectors and partitions them into n roughly equal sized partitions then adds all records in that partition to an index data structure and you end up with n indices

During querying by default every record gets sent to every index to produce the top k results, then those are aggregated and the best results from all partitions are kept.

if you set replicas to 2 it will load the same index twice and records will be randomly sent to one of the two indices, both speeding up the search and reducing the about of records that end up in a single partition

**Comment by maksle** [comment]
I bumped down to 128gb machines because of difficulties provisioning enough 256gb machines in my region, but I think it should be sufficient really. However, I'm still having problems. I have gotten rid of the VectorConverter from the pipeline, and reduced to 30 partitions using 30 executors. That produced a much smaller index (3gb total, split across 30 smaller indices). Then I did as follows:

```
model = PipelineModel.load(model_hnsw_path)
hnsw_stage = model.stages[-1]
hnsw_stage.setNumReplicas(2)
output = model.transform(query)  # 30 shards query df
```

But I'm still getting lost nodes, with errors looking like this:

```
22/09/09 02:20:53 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 3 for reason Container marked as failed: container_1662685320529_0001_01_000006 on host: ip-172-31-30-154.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node.
22/09/09 02:20:53 ERROR YarnClusterScheduler: Lost executor 3 on ip-172-31-30-154.ec2.internal: Container marked as failed: container_1662685320529_0001_01_000006 on host: ip-172-31-30-154.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node.
22/09/09 02:20:56 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 19 for reason Container marked as failed: container_1662685320529_0001_01_000038 on host: ip-172-31-31-70.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node.
22/09/09 02:20:56 ERROR YarnClusterScheduler: Lost executor 19 on ip-172-31-31-70.ec2.internal: Container marked as failed: container_1662685320529_0001_01_000038 on host: ip-172-31-31-70.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node.
```

In Spark history the active stage with failures has this description
`map at KnnAlgorithm.scala:521`

**Comment by jelmerk** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/emr-exit-status-100-lost-node/

> This error commonly occurs during either of the following situations:
> 
> A core or task node is terminated because of high disk space utilization.
> A node becomes unresponsive due to prolonged high CPU utilization or low available memory

If the garbage collection looks ok in the spark ui you might need to enable termination protection

**Comment by maksle** [comment]
You are right, it turns out that the nodes are dropping due to insufficient disk space. But this is strange -- I tried bumping up the disk space to 1tb per node (4 volumes x 256gb/volume) and it still occurs. If <25% of the nodes are healthy (<90% capacity) it will drop the node. Do you think it makes sense that so much disk space should be needed during the `map at KnnAlgorithm.scala:521` stage?

**Comment by jelmerk** [comment]
Check if there are any files left in the folder defined under the `spark.hnswlib.settings.index.cache_folder` property by default this points to `/tmp`

**Comment by maksle** [comment]
That command replies that /tmp/hnsw_* doesn't exist. I checked a few nodes manually and they don't have any directories like that.

I doubled the volume size again to 2tb per node and it gets past that stage, though it sometimes still loses nodes due to disk space. On this stage that just had lost nodes, the stats are:
```
Shuffle Read Size / Records: 254.2 GiB / 1919019840
Shuffle Write Size / Records: 6.0 TiB / 57570595200
```
Since I have 30 nodes x 2TiB each, I should be OK?

BTW, as an aside, I do wonder how this library is the only Spark ANN game in town. I guess others must be just running a service running FAISS or other on GPU and calling it with mapPartitions? I'm guessing that getting these things working well on Spark without a lot of opinionated decisions is difficult. Curious to get your 2 cents.

**Comment by maksle** [comment]
Reduced query size to only 50k and still get lost nodes due to disk space during `map at KnnAlgorithm.scala:521`. I doubt changing `ef` or other parameters would help here, correct? I would like to know some guidelines for those though!

**Comment by maksle** [comment]
I wasn't able to resolve the inordinate disk space issue so I have switched over to using hnswlib in a separate service that is called from Spark. I do appreciate your attention to the matter and hope that the issue was user error on my part somewhere.
