### ISSUE TITLE
Unable to update index

### ISSUE THREAD

**Issue by deil87** [jelmerk/hnswlib#53]
Hello,

There is a way to store a fitted HnswSimilarity model but I haven't found a way to update it with new vectors.

Is there a way or work around, plans to add this soon?

Thank you!

**Comment by jelmerk** [comment]
Hey that would be easy enough to implement if it was clear what the api for that would look like.

Have you seen any other ml lib models support incremental updates ? Because I can't think of any of the top of my head

**Comment by jelmerk** [comment]
Looks like [kmeans and gmm have an initialModel property](https://stackoverflow.com/questions/41192799/whether-we-can-update-existing-model-in-spark-ml-spark-mllib), which is not quite the same but i guess a similar approach could work

I can see if i can find some time over the weekend to try this out

**Comment by jelmerk** [comment]
This is supported now in 1.1.0

For an example see :

https://github.com/jelmerk/hnswlib/blob/master/hnswlib-pyspark/tests/test_integration.py#L9
