### ISSUE TITLE
scala 2.12 port running very slowly

### ISSUE THREAD

**Issue by sudhanshugarg** [jelmerk/hnswlib#56]
When this library was used for computing KNN with scala 2.11, spark 2.3.0, it used to take 2.5 hrs.
With the same settings, (input data size, executors, executory memory etc.), with scala 2.12, spark 3.1.1, it takes 53 hrs and still running (killed the job).

I believe there is some `.rdd` conversion that is causing all the contents to be flushed to disk. Could you please help narrow down the root cause, so we may continue to use this library.

Here is the code being used:

```
    val converter = new VectorConverter()
      .setInputCol("inputFeatures")
      .setOutputCol("features")

    val normalizer = new Normalizer()
      .setInputCol("features")
      .setOutputCol("normalizedFeatures")

    val hnsw =  new HnswSimilarity()
        .setIdentifierCol("myid")
        .setQueryIdentifierCol("myid")
        .setFeaturesCol("normalizedFeatures")
        .setNumPartitions(numPartitions)
        .setNumReplicas(numReplicas)
        .setM(m)
        .setEf(ef)
        .setEfConstruction(efConstruction)
        .setK(topK)
        .setDistanceFunction(distanceFunction)
        .setSimilarityThreshold(similarityThreshold)
        .setPredictionCol("pred")
        .setExcludeSelf(excludeSelf)

    val pipeline = new Pipeline()
      .setStages(Array(converter, normalizer, hnsw))

    val hnswModel = pipeline.fit(indexItems)
    val output = hnswModel.transform(indexItems)
```

**Comment by jelmerk** [comment]
Which version did you use before ?

**Comment by sudhanshugarg** [comment]
Earlier we used:
com.github.jelmerk:hnswlib-spark_2.3.0_2.11:0.0.46

Now we're using:
com.github.jelmerk:hnswlib-spark_3.1_2.12:1.0.1

**Comment by jelmerk** [comment]
Could you try with `new HnswSimilarity().setParallelism(0)`

**Comment by sudhanshugarg** [comment]
okay let me try. One other thing, if I look at the spark UI. The stage that takes 8.2 hrs with spark 3.1.1 and the same stage with spark 2.3.0 takes 60 mins.

The line it says has an issue is: `[rdd at KnnAlgorithm.scala:473]`

Earlier with spark 2.3.0, `input` was 15.2GB and `Shuffle write` was 81.2GB. For the same stage, with spark 3.1.1, `input` was 15.2GB and `Shuffle write` was 65.4TB.

**Comment by jelmerk** [comment]
Ok if it does not work can you attach the spark event log

**Comment by sudhanshugarg** [comment]
@jelmerk yes it worked with setParallelism(0). Could you please help explain what happened ?

**Comment by jelmerk** [comment]
setParallelism [defines the number of cpu cores](https://github.com/jelmerk/hnswlib/blob/master/hnswlib-spark/src/main/scala/com/github/jelmerk/spark/knn/KnnAlgorithm.scala#L539) the KNN task will utilise on an executor. In the old version it used the maximum number available on the executor.  But spark tasks are supposed to be single threaded so unless your cluster uses something like [cgroups](https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/NodeManagerCgroups.html) the tasks are not being a good neighbour and are using more resources than they should

So the behaviour was changed to use the value of `spark.task.cpus` as the default parallelism. If it is undefined it will use 1 cpu core per task. The defaults can be overwritten with setParallelism.  Setting it to 0 makes it use all available cpu's

You should follow the [suggested configuration](https://github.com/jelmerk/hnswlib/tree/master/hnswlib-spark#suggested-configuration)

Set executor.instances to the number of partitions, define spark.task.cpus as the number of spark executor cores.  and set the number of executor cores as high as possible
