### ISSUE TITLE
How can I add more items to the index?

### ISSUE THREAD

**Issue by DoanThu** [jelmerk/hnswlib#6]
I ran this:
`hnsw = Hnsw(identifierCol='ID', vectorCol='features', distanceFunction='cosine', m=64, ef=5, k=5, efConstruction=200, numPartitions=100)`
`model = hnsw.fit(df)`
Now I want to save 'model' as an index file so that later I can read that file back and add more data into it (add extra_df for example).
Can you please tell me how can I do that? I have looked up in the repo but no example is found.

**Comment by jelmerk** [comment]
Right now that is not supported. If you have any concrete ideas about what this should look like (possibly ising other spark libs as an example) feel free to suggest an improvement and i’ll see if i can add it

**Comment by UlfbertHuynh** [comment]
Actually you can adopt the idea of a multiple-segment index. So for example if you are building the index for the first time you save it down as one segment and then the next time you can add more data by insert these data into a new segment and then save down as a new segment.
Then at search time just use multiple thread to conduct search on the whole index (multiple segments) concurrently then use K-way merging to get the final result.
We are building a new library based on this idea. Checkout:
https://github.com/UlfbertHuynh/Scalable_hnsw

**Comment by jelmerk** [comment]
That's what the pyspark index actually does. It repartitions the data and then on each partition it creates an index containing the elements in that partition. 

When you query the index you ask all of the partitions to find the best matches, those results are aggregated and then only the best matches are returned

**Comment by UlfbertHuynh** [comment]
Oh my bad, so that solved issue then. I have been paying attention to your Java implementation only since that's what our techstack use.
