### ISSUE TITLE
Brute Force vs hnsw Problem

### ISSUE THREAD

**Issue by ccalvin97** [jelmerk/hnswlib#60]
When I tried to compared the recall between brute force function and hnsw, I found the recall is zero.

I randomly picked 1000 data for the testing for both brute force and hnsw and tried to see how many pairs are the same from both functions. 

I am curious about your brute force function. Is it calculating all of the pairs and then rank them right?

Here's my code
hnsw = HnswSimilarity(identifierCol='ITEM_ID',featuresCol='EMBEDDINGS', distanceFunction='euclidean', m=32, ef=5, k=10,ef    Construction=200, numPartitions=100, excludeSelf=False, similarityThreshold=-1.0, predictionCol='pred')
brute_force = BruteForceSimilarity(identifierCol='ITEM_ID', featuresCol='EMBEDDINGS',distanceFunction='euclidean',k=10, n    umPartitions=100, excludeSelf=False, similarityThreshold=-1.0, predictionCol='pred')

**Comment by jelmerk** [comment]
brute force  does a pairwise comparison. so it will compare each embedding in the set with each other embedding.

On spark you can use [KnnSimilarityEvaluator] to evaluate the accuracy (https://github.com/jelmerk/hnswlib/tree/1db01192c7d53de7d7de81a83da11a4fe90fd37d/hnswlib-pyspark)

Or do it by hand as you did

**Comment by ccalvin97** [comment]
Thanks for your reply. I am curious about, in general, how much recall can this model reach in small dataset like 1000-10000? thanks

**Comment by jelmerk** [comment]
depends on how similar items are. if the best match is like 0.5 and the worst 0.45 its not going to perform that well
