### ISSUE TITLE
cannot calculate resize correctly leading to SizeLimitExceededException

### ISSUE THREAD

**Issue by elim27** [jelmerk/hnswlib#64]
Hi -- 

`HnswIndex` method [size](https://github.com/jelmerk/hnswlib/blob/1db01192c7d53de7d7de81a83da11a4fe90fd37d/hnswlib-core/src/main/java/com/github/jelmerk/knn/hnsw/HnswIndex.java#L117) returns the size of the underlying data structure `lookup` , but throwing a `SizeLimitExceededException` is contingent on whether `nodeCount` is greater that the `maxItemCount` when calling [add](https://github.com/jelmerk/hnswlib/blob/1db01192c7d53de7d7de81a83da11a4fe90fd37d/hnswlib-core/src/main/java/com/github/jelmerk/knn/hnsw/HnswIndex.java#L246-L248).  This is an issue when removals occur since `nodeCount` stays the same yet the size of lookup [decreases](https://github.com/jelmerk/hnswlib/blob/1db01192c7d53de7d7de81a83da11a4fe90fd37d/hnswlib-core/src/main/java/com/github/jelmerk/knn/hnsw/HnswIndex.java#L190). 

Callers cannot accurately calculate whether or not to resize an index due to misleading index size.

**Comment by jelmerk** [comment]
thats correct, unfortunately this is a limitation because deletes are "soft deletes" the only way right now to get rid of them is to do a re-index

This is also why support for deletes is disabled by default and listed as "experimental support"

**Comment by Blizzara** [comment]
@jelmerk would you be open to exposing the nodeCount as a method? That'd allow clients to do resizing properly and then e.g. periodically reindexing when the nodeCount grows over size by some threshold
