### ISSUE TITLE
support for num_threads parameter while building the index

### ISSUE THREAD

**Issue by siddhsql** [jelmerk/hnswlib#65]
does this library have support for any num_threads parameter while building the index like the C++ implementation? i couldn't find any. also does it support deletion like the C++ implementation?

**Comment by jelmerk** [comment]
There is a `[addAll](https://javadoc.io/static/com.github.jelmerk/hnswlib-core/1.1.0/com/github/jelmerk/knn/Index.html#addAll-java.util.Collection-int-com.github.jelmerk.knn.ProgressListener-int-)([Collection](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html?is-external=true)<[TItem](https://javadoc.io/static/com.github.jelmerk/hnswlib-core/1.1.0/com/github/jelmerk/knn/Index.html)> items, int numThreads, [ProgressListener](https://javadoc.io/static/com.github.jelmerk/hnswlib-core/1.1.0/com/github/jelmerk/knn/ProgressListener.html) listener, int progressUpdateInterval) method you can use
