### ISSUE TITLE
If there is no near similar items. What is the output?

### ISSUE THREAD

**Issue by ccalvin97** [jelmerk/hnswlib#70]
Hi, thanks for your work. I am curious about if I set similarityThreshold very very small and distanceFunction='euclidean'

---------------------------------------------------------
Let's say, there is no near similar items from ItemA.  
Then, what is the output of this specific ItemA? 
The Algo will output empty and ignore this ItemA? 

many thanks

**Comment by jelmerk** [comment]
you'll just get an empty collection of neighbours
